### ISSUE TITLE
Uso correto do g_cclosure_new_swap

### ISSUE THREAD

**Issue by scorninpc** [UFG-EC-ED1/EC-ED1-2019#1]
Primeiramente, excelente material. Conheci por um acaso, e ja repasse para varios amigos. 

Mas encontrei por que estou procurando mais sobre g_cclosure_new_swap. 

Na aula 11, voce utiliza o new_swap enviando o primeiro parâmetro como o user_data. 

https://github.com/UFG-EC-ED1/EC-ED1-2019/blob/cbd25a6d18cf110afe04b6beaffdb62c164d1853/Aula11/Exemplos/undo/main.c#L228

Digo, na documentação diz:

> Creates a new closure which invokes callback_func with user_data as the first parameter.

E tudo parece correto.

Porem não consigo encontrar em lugar algum, como ficam os outros parametros. Ja procurei até o src do GObject, porem la está como va_list,  definido como user_function(gpointer, ...)

Teria alguma informação complementar sobre o restante dos argumentos? por exemplo, o signal "button-release" possui o GdkEventButton. Como recupera-lo?

ps: desculpa postar como um issue, se tiver problemas eu mesmo apago, mas como é referente à aulas, tomei como principio que eu poderia ter ajuda aqui ja que não consigo em nenhum outro lugar, nem no [stackoverflow](https://stackoverflow.com/questions/56105233/is-there-an-way-to-ignore-signals-signature)

**Comment by gcms** [comment]
Olá Bruno. Esse código foi apenas um exemplo para aos alunos de como utilizar uma pilha pra implementar operações de desfazer/refazer em um editor de texto.

Pelo que entendi da documentação o swap simplesmente inverte a ordem dos parâmetros, de modo que o restante dos argumentos vem logo em seguida na pilha de execução, ou seja, bastaria você declarar outros parâmetros na função de callback.

Eu utilizei esse g_cclosure_new_swap() porque eu só precisava do user_data na minha callback. Se você precisa dos demais parâmetros talvez poderia usar o g_cclosure_new(), neste caso o user_data vem após todos os outros parâmetros.

**Comment by scorninpc** [comment]
Oi.

Eu preciso abstrair o callback. Terei um numero indeterminado de widgets e de connects. A unica coisa que tenho certeza é que terá o user_data, por isso o swap veio a calhar. Meu problema é que não sei como verificar qual o tipo do segundo, terceiro argumento, ..., pois seriam um gpointer (void **), não da pra simplesmente dar o cast para GdkEventButton, por que se for outro signal, talvez seja um gchar *

Mas qualquer maneira continuo firme na busca, obrigado hahahaha

**Comment by scorninpc** [comment]
Oi. Só para documentar, consegui resolver o problema utilizando argumentos dinamicos e g_signal_query.

Antes de chamar o G_CALLBACK, eu recupero os parametros do signal e adiciono no user_data

```
g_signal_query(g_signal_lookup (callback_event, G_OBJECT_TYPE (instance)), &signal_info);
callback_object->signal_id = signal_info.signal_id;
callback_object->signal_name = signal_info.signal_name;
callback_object->itype = signal_info.itype;
callback_object->signal_flags = signal_info.signal_flags;
callback_object->return_type = signal_info.return_type;
callback_object->n_params = signal_info.n_params;
callback_object->param_types = signal_info.param_types;

GClosure  *closure;
closure = g_cclosure_new_swap (G_CALLBACK (connect_callback), callback_object, NULL);
int ret = g_signal_connect_closure (instance, callback_event, closure, TRUE);
```

Depois no callback, eu recupero a assinatura do signal,e percorro os parâmetros


```
bool connect_callback(gpointer user_data, ...) 
{
    // Return to st_callback
    struct st_callback *callback_object = (struct st_callback *) user_data;

    // Get param counter from g_signal_query, to loop casting types and store into internal_parameters
    int param_count = callback_object->n_params;
    va_list ap;
    va_start(ap, user_data);

    // Loop into param_types of GSignalQuery from g_signal_query
    for (int i=0; i<param_count; i++) {

        switch (G_TYPE_FUNDAMENTAL(callback_object->param_types[i])) {
            case G_TYPE_CHAR:
                
                break;
            case G_TYPE_UCHAR:
                
                break;
            case G_TYPE_STRING:
                
                break;
            case G_TYPE_OBJECT:
                
                break;
            case G_TYPE_POINTER:
                
                break;
            case G_TYPE_INTERFACE: 
                
                break;
            case G_TYPE_PARAM:
                
                break;
            case G_TYPE_BOXED:
                break;
        }
        
    }

    va_end(ap);
}

```

Já que eu levantei o problema, achei interessante postar a solução. Obrigado
